Fix trait bound not satisfied
```
 error[E0599]: the method `read_to_end` exists for opaque type `impl AsyncRead + Send`, but its trait bounds were not satisfied
  --> lambda-smtp-relay/./handler.rs:78:6
   |
68 | /     s3.get_object(GetObjectRequest {
69 | |         bucket: env::var("S3_BUCKET").expect("Missing $S3_BUCKET"),
70 | |         key: message_id.into(),
71 | |         ..Default::default()
...  |
77 | |     .into_async_read()
78 | |     .read_to_end(&mut content)
   | |     -^^^^^^^^^^^ method cannot be called on `impl AsyncRead + Send` due to unsatisfied trait bounds
   | |_____|
   |
   |
   = note: the following trait bounds were not satisfied:
           `impl tokio::io::async_read::AsyncRead + Send: AsyncRead`
           which is required by `impl tokio::io::async_read::AsyncRead + Send: AsyncReadExt`
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  + use tokio::io::util::async_read_ext::AsyncReadExt;
   |

warning: unused import: `tokio::io::AsyncReadExt`
  --> lambda-smtp-relay/./handler.rs:20:5
   |
20 | use tokio::io::AsyncReadExt;
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
```